backend:
  name: github
  repo: ishchow/artishchow.com
  branch: main

media_libraries:
  cloudflare_r2:
    access_key_id: 2e88c7cef5bad24c596afef420546f76
    bucket: artishchow-images
    account_id: c0b3bb517c4604eae20009c074ba284b
    public_url: https://images.artishchow.com

collections:
  - name: artwork
    label: Artwork
    label_singular: Artwork
    folder: content/artwork
    path: "{{slug}}/index"
    create: true
    extension: md
    format: toml-frontmatter
    fields:
      - { label: Title, name: title, widget: string }
      - { label: Description, name: description, widget: string, required: false }
      - { label: Date, name: date, widget: datetime, format: "YYYY-MM-DD", date_format: "YYYY-MM-DD", time_format: false }
      - label: Tags
        name: taxonomies.tags
        widget: list
        allow_add: true
        required: false
      - { label: Thumbnail, name: extra.thumbnail, widget: image, hint: "800x800 thumbnail image" }
      - { label: Body, name: body, widget: markdown }
